export interface QuestionOption {
  key: 'A' | 'B' | 'C' | 'D';
  textEs: string;
  textHy: string;
}

export interface QuestionItem {
  id: number;
  questionEs: string;
  questionHy: string;
  options: QuestionOption[];
  correctKey: 'A' | 'B' | 'C' | 'D';
  tenseFocus: 'Pretérito Perfecto' | 'Pretérito Indefinido' | 'Pretérito Imperfecto';
  tenseFocusHy: 'Անկատար ներկա / Վաղակատար' | 'Անցյալ կատարյալ' | 'Անցյալ անկատար';
  timeMarker: string;
  grammarTipEs: string;
  grammarTipHy: string;
  prizeAmount: number;
  prizeDisplay: string;
  isMilestone?: boolean;
}

export const PRIZE_LADDER: { level: number; amount: number; display: string; isMilestone: boolean }[] = [
  { level: 1, amount: 500, display: '€500', isMilestone: false },
  { level: 2, amount: 1000, display: '€1.000', isMilestone: false },
  { level: 3, amount: 2000, display: '€2.000', isMilestone: false },
  { level: 4, amount: 3000, display: '€3.000', isMilestone: false },
  { level: 5, amount: 5000, display: '€5.000', isMilestone: true },
  { level: 6, amount: 7500, display: '€7.500', isMilestone: false },
  { level: 7, amount: 10000, display: '€10.000', isMilestone: false },
  { level: 8, amount: 15000, display: '€15.000', isMilestone: false },
  { level: 9, amount: 20000, display: '€20.000', isMilestone: false },
  { level: 10, amount: 30000, display: '€30.000', isMilestone: true },
  { level: 11, amount: 40000, display: '€40.000', isMilestone: false },
  { level: 12, amount: 50000, display: '€50.000', isMilestone: false },
  { level: 13, amount: 65000, display: '€65.000', isMilestone: false },
  { level: 14, amount: 80000, display: '€80.000', isMilestone: false },
  { level: 15, amount: 100000, display: '€100.000', isMilestone: true },
  { level: 16, amount: 125000, display: '€125.000', isMilestone: false },
  { level: 17, amount: 150000, display: '€150.000', isMilestone: false },
  { level: 18, amount: 175000, display: '€175.000', isMilestone: false },
  { level: 19, amount: 200000, display: '€200.000', isMilestone: false },
  { level: 20, amount: 250000, display: '€250.000', isMilestone: true },
  { level: 21, amount: 300000, display: '€300.000', isMilestone: false },
  { level: 22, amount: 350000, display: '€350.000', isMilestone: false },
  { level: 23, amount: 400000, display: '€400.000', isMilestone: false },
  { level: 24, amount: 450000, display: '€450.000', isMilestone: false },
  { level: 25, amount: 500000, display: '€500.000', isMilestone: true },
  { level: 26, amount: 600000, display: '€600.000', isMilestone: false },
  { level: 27, amount: 700000, display: '€700.000', isMilestone: false },
  { level: 28, amount: 800000, display: '€800.000', isMilestone: false },
  { level: 29, amount: 900000, display: '€900.000', isMilestone: false },
  { level: 30, amount: 1000000, display: '€1.000.000', isMilestone: true },
];

export const QUESTIONS_DATA: QuestionItem[] = [
  {
    id: 1,
    questionEs: '¿Cuántos goles has marcado esta semana?',
    questionHy: 'Քանի՞ գոլ ես խփել այս շաբաթ։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'esta semana (այս շաբաթ)',
    grammarTipEs: 'Usamos Pretérito Perfecto (he + participio) para un período de tiempo no terminado: "esta semana".',
    grammarTipHy: 'Օգտագործվում է Pretérito Perfecto (he marcado), քանի որ ժամանակահատվածը դեռ չի ավարտվել՝ «esta semana» (այս շաբաթ)։',
    prizeAmount: 500,
    prizeDisplay: '€500',
    correctKey: 'A',
    options: [
      { key: 'A', textEs: 'He marcado tres goles.', textHy: 'Երեք գոլ եմ խփել։' },
      { key: 'B', textEs: 'Marqué tres goles ayer.', textHy: 'Երեկ երեք գոլ խփեցի։' },
      { key: 'C', textEs: 'Marcaba tres goles.', textHy: 'Երեք գոլ էի խփում։' },
      { key: 'D', textEs: 'Marco tres goles.', textHy: 'Երեք գոլ եմ խփում։' },
    ],
  },
  {
    id: 2,
    questionEs: '¿Qué hiciste después del partido de ayer?',
    questionHy: 'Ի՞նչ արեցիր երեկվա խաղից հետո։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'ayer (երեկ)',
    grammarTipEs: 'Usamos Pretérito Indefinido (fui, descansé) para acciones concretas y terminadas en un tiempo pasado cerrado: "ayer".',
    grammarTipHy: 'Օգտագործվում է Pretérito Indefinido (fui, descansé), քանի որ գործողությունն ավարտված է որոշակի անցյալ պահին՝ «ayer» (երեկ)։',
    prizeAmount: 1000,
    prizeDisplay: '€1.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'He descansado ahora.', textHy: 'Հիմա հանգստացել եմ։' },
      { key: 'B', textEs: 'Fui a casa y descansé.', textHy: 'Գնացի տուն և հանգստացա։' },
      { key: 'C', textEs: 'Iba a casa todos los días.', textHy: 'Ամեն օր տուն էի գնում։' },
      { key: 'D', textEs: 'Voy a casa.', textHy: 'Գնում եմ տուն։' },
    ],
  },
  {
    id: 3,
    questionEs: '¿Dónde jugabas cuando eras pequeño?',
    questionHy: 'Որտե՞ղ էիր խաղում, երբ փոքր էիր։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'cuando eras pequeño (երբ փոքր էիր)',
    grammarTipEs: 'Usamos Pretérito Imperfecto (jugaba) para hábitos repetidos o situaciones continuas en el pasado.',
    grammarTipHy: 'Օգտագործվում է Pretérito Imperfecto (jugaba), քանի որ խոսքը մանկության սովորական, կրկնվող գործողության մասին է։',
    prizeAmount: 2000,
    prizeDisplay: '€2.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'He jugado en el estadio.', textHy: 'Մարզադաշտում եմ խաղացել։' },
      { key: 'B', textEs: 'Jugué ayer en el parque.', textHy: 'Երեկ այգում խաղացի։' },
      { key: 'C', textEs: 'Jugaba en el parque de mi barrio.', textHy: 'Խաղում էի իմ թաղամասի այգում։' },
      { key: 'D', textEs: 'Juego en el parque.', textHy: 'Այգում եմ խաղում։' },
    ],
  },
  {
    id: 4,
    questionEs: '¿Has entrenado hoy?',
    questionHy: 'Այսօր մարզվե՞լ ես։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'hoy / esta mañana (այսօր / այսօր առավոտյան)',
    grammarTipEs: 'La pregunta usa "hoy" (tiempo abierto), por lo que respondemos en Pretérito Perfecto: "he entrenado esta mañana".',
    grammarTipHy: 'Հարցում կա «hoy» (այսօր)՝ դեռ չավարտված օր, ուստի պատասխանում ենք Pretérito Perfecto-ով՝ «he entrenado»։',
    prizeAmount: 3000,
    prizeDisplay: '€3.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Entrené la semana pasada.', textHy: 'Անցած շաբաթ մարզվեցի։' },
      { key: 'B', textEs: 'Entrenaba cada mañana.', textHy: 'Ամեն առավոտ մարզվում էի։' },
      { key: 'C', textEs: 'Sí, he entrenado esta mañana.', textHy: 'Այո, այսօր առավոտյան մարզվել եմ։' },
      { key: 'D', textEs: 'Entreno mañana.', textHy: 'Վաղը մարզվում եմ։' },
    ],
  },
  {
    id: 5,
    questionEs: '¿Quién marcó el gol decisivo ayer?',
    questionHy: 'Ո՞վ խփեց որոշիչ գոլը երեկ։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'ayer (երեկ)',
    grammarTipEs: 'Para un evento puntual ocurrido en el día anterior ("ayer"), se emplea Pretérito Indefinido: "marcó".',
    grammarTipHy: '«Ayer» (երեկ) ժամանակային նշիչով եզակի, ավարտված դեպքի համար գործածվում է Pretérito Indefinido՝ «marcó»։',
    prizeAmount: 5000,
    prizeDisplay: '€5.000',
    isMilestone: true,
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Ha marcado Carlos esta semana.', textHy: 'Կառլոսն այս շաբաթ գոլ է խփել։' },
      { key: 'B', textEs: 'Carlos marcó el gol decisivo.', textHy: 'Կառլոսը խփեց որոշիչ գոլը։' },
      { key: 'C', textEs: 'Carlos marcaba muchos goles.', textHy: 'Կառլոսը շատ գոլեր էր խփում։' },
      { key: 'D', textEs: 'Carlos marca goles.', textHy: 'Կառլոսը գոլեր է խփում։' },
    ],
  },
  {
    id: 6,
    questionEs: '¿Cómo era tu primer entrenador?',
    questionHy: 'Ինչպիսի՞ն էր քո առաջին մարզիչը։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'descripción en el pasado (նկարագրություն անցյալում)',
    grammarTipEs: 'Para describir el carácter o rasgos de una persona en el pasado usamos Imperfecto: "era exigente, pero amable".',
    grammarTipHy: 'Անցյալում մարդու բնավորության կամ հատկանիշների նկարագրության համար օգտագործվում է Imperfecto՝ «era» (էր)։',
    prizeAmount: 7500,
    prizeDisplay: '€7.500',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Fue al estadio ayer.', textHy: 'Երեկ գնաց մարզադաշտ։' },
      { key: 'B', textEs: 'Ha sido entrenador esta semana.', textHy: 'Այս շաբաթ մարզիչ է եղել։' },
      { key: 'C', textEs: 'Era exigente, pero muy amable.', textHy: 'Պահանջկոտ էր, բայց շատ բարի։' },
      { key: 'D', textEs: 'Es exigente.', textHy: 'Պահանջկոտ է։' },
    ],
  },
  {
    id: 7,
    questionEs: '¿Has jugado alguna vez de portero?',
    questionHy: 'Երբևէ դարպասապահ խաղացե՞լ ես։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'alguna vez / experiencia de vida (կյանքի փորձ)',
    grammarTipEs: 'Para experiencias vitales ("alguna vez / algunas veces"), usamos Pretérito Perfecto: "he jugado".',
    grammarTipHy: 'Կյանքի փորձի մասին խոսելիս («երբևէ / մի քանի անգամ») կիրառվում է Pretérito Perfecto՝ «he jugado»։',
    prizeAmount: 10000,
    prizeDisplay: '€10.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Jugué de portero ayer solamente.', textHy: 'Միայն երեկ դարպասապահ խաղացի։' },
      { key: 'B', textEs: 'Jugaba de delantero.', textHy: 'Հարձակվող էի խաղում։' },
      { key: 'C', textEs: 'Sí, he jugado de portero algunas veces.', textHy: 'Այո, մի քանի անգամ դարպասապահ եմ խաղացել։' },
      { key: 'D', textEs: 'Juego de portero mañana.', textHy: 'Վաղը դարպասապահ եմ խաղում։' },
    ],
  },
  {
    id: 8,
    questionEs: '¿Qué pasó en el minuto 80 del último partido?',
    questionHy: 'Ի՞նչ տեղի ունեցավ վերջին խաղի 80-րդ րոպեին։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'en el minuto 80 (80-րդ րոպեին՝ կոնկրետ ակնթարթ)',
    grammarTipEs: 'Un suceso preciso y terminado en un momento exacto del partido ("en el minuto 80") requiere Indefinido: "marcó".',
    grammarTipHy: 'Խաղի հստակ պահին (80-րդ րոպեին) կատարված ավարտուն դեպքը պահանջում է Indefinido՝ «marcó»։',
    prizeAmount: 15000,
    prizeDisplay: '€15.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Hemos marcado este mes.', textHy: 'Այս ամիս գոլ ենք խփել։' },
      { key: 'B', textEs: 'Marcábamos normalmente.', textHy: 'Սովորաբար գոլ էինք խփում։' },
      { key: 'C', textEs: 'Nuestro delantero marcó un gol.', textHy: 'Մեր հարձակվողը գոլ խփեց։' },
      { key: 'D', textEs: 'Nuestro delantero marca.', textHy: 'Մեր հարձակվողը գոլ է խփում։' },
    ],
  },
  {
    id: 9,
    questionEs: '¿Qué hacías antes de cada partido cuando eras niño?',
    questionHy: 'Ի՞նչ էիր անում յուրաքանչյուր խաղից առաջ, երբ փոքր էիր։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'siempre / antes de cada partido (միշտ / յուրաքանչյուր խաղից առաջ)',
    grammarTipEs: 'Rutina repetitiva en la infancia ("siempre..."): Pretérito Imperfecto: "calentaba".',
    grammarTipHy: '«Siempre» (միշտ) բառով անցյալի կանոնավոր սովորությունը դրվում է Imperfecto-ով՝ «calentaba» (տաքացում էի անում)։',
    prizeAmount: 20000,
    prizeDisplay: '€20.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'He escuchado al entrenador hoy.', textHy: 'Այսօր լսել եմ մարզչին։' },
      { key: 'B', textEs: 'Escuché al entrenador ayer.', textHy: 'Երեկ լսեցի մարզչին։' },
      { key: 'C', textEs: 'Siempre calentaba durante quince minutos.', textHy: 'Միշտ տասնհինգ րոպե տաքացում էի անում։' },
      { key: 'D', textEs: 'Caliento ahora.', textHy: 'Հիմա տաքացում եմ անում։' },
    ],
  },
  {
    id: 10,
    questionEs: '¿Habéis ganado algún partido este mes?',
    questionHy: 'Այս ամիս որևէ խաղ հաղթե՞լ եք։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'este mes (այս ամիս)',
    grammarTipEs: '"Este mes" es un período temporal actual no concluido, por lo que usamos Pretérito Perfecto: "hemos ganado".',
    grammarTipHy: '«Este mes» (այս ամիս) դեռ ընթացիկ ժամանակ է, ուստի օգտագործվում է Pretérito Perfecto՝ «hemos ganado»։',
    prizeAmount: 30000,
    prizeDisplay: '€30.000',
    isMilestone: true,
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Ganamos el año pasado.', textHy: 'Անցած տարի հաղթեցինք։' },
      { key: 'B', textEs: 'Ganábamos mucho antes.', textHy: 'Նախկինում հաճախ էինք հաղթում։' },
      { key: 'C', textEs: 'Sí, hemos ganado dos partidos.', textHy: 'Այո, երկու խաղ ենք հաղթել։' },
      { key: 'D', textEs: 'Ganamos mañana.', textHy: 'Վաղը հաղթում ենք։' },
    ],
  },
  {
    id: 11,
    questionEs: '¿Por qué saliste del campo ayer?',
    questionHy: 'Ինչո՞ւ երեկ դուրս եկար խաղադաշտից։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'ayer (երեկ)',
    grammarTipEs: 'Acciones concluidas en el partido de ayer ("salí", "me lesioné"): Pretérito Indefinido.',
    grammarTipHy: 'Երեկվա խաղի ավարտուն պատճառահետևանքային գործողություններ («salí», «me lesioné»)՝ Pretérito Indefinido։',
    prizeAmount: 40000,
    prizeDisplay: '€40.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'He salido muchas veces.', textHy: 'Շատ անգամ եմ դուրս եկել։' },
      { key: 'B', textEs: 'Salí porque me lesioné la pierna.', textHy: 'Դուրս եկա, որովհետև ոտքս վնասեցի։' },
      { key: 'C', textEs: 'Salía siempre temprano.', textHy: 'Միշտ շուտ էի դուրս գալիս։' },
      { key: 'D', textEs: 'Salgo porque estoy cansado.', textHy: 'Դուրս եմ գալիս, որովհետև հոգնած եմ։' },
    ],
  },
  {
    id: 12,
    questionEs: '¿Qué posición jugabas normalmente en tu antiguo equipo?',
    questionHy: 'Նախկին թիմում սովորաբար ո՞ր դիրքում էիր խաղում։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'normalmente en tu antiguo equipo (սովորաբար նախկինում)',
    grammarTipEs: 'Hábito continuo y regular en una época pasada ("normalmente"): Pretérito Imperfecto ("jugaba").',
    grammarTipHy: '«Normalmente» (սովորաբար) բառը ցույց է տալիս անցյալի կանոնավոր դիրքը, ուստի՝ Imperfecto («jugaba»)։',
    prizeAmount: 50000,
    prizeDisplay: '€50.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'He jugado hoy de defensa.', textHy: 'Այսօր պաշտպան եմ խաղացել։' },
      { key: 'B', textEs: 'Jugué de portero el domingo.', textHy: 'Կիրակի դարպասապահ խաղացի։' },
      { key: 'C', textEs: 'Normalmente jugaba de centrocampista.', textHy: 'Սովորաբար կիսապաշտպան էի խաղում։' },
      { key: 'D', textEs: 'Juego de delantero.', textHy: 'Հարձակվող եմ խաղում։' },
    ],
  },
  {
    id: 13,
    questionEs: '¿Has hablado hoy con el entrenador?',
    questionHy: 'Այսօր խոսե՞լ ես մարզչի հետ։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'hoy (այսօր)',
    grammarTipEs: 'Acción dentro del marco temporal del día de hoy ("hoy"): Pretérito Perfecto ("he hablado").',
    grammarTipHy: 'Այսօրվա օրվա մեջ տեղի ունեցած խոսակցության համար օգտագործվում է Pretérito Perfecto («he hablado»)։',
    prizeAmount: 65000,
    prizeDisplay: '€65.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Hablé con él el lunes pasado.', textHy: 'Անցած երկուշաբթի նրա հետ խոսեցի։' },
      { key: 'B', textEs: 'Hablaba con él cada día.', textHy: 'Ամեն օր նրա հետ խոսում էի։' },
      { key: 'C', textEs: 'Sí, he hablado con él después del entrenamiento.', textHy: 'Այո, մարզումից հետո նրա հետ խոսել եմ։' },
      { key: 'D', textEs: 'Hablo con él mañana.', textHy: 'Վաղը խոսում եմ նրա հետ։' },
    ],
  },
  {
    id: 14,
    questionEs: '¿Cómo terminó el partido del domingo pasado?',
    questionHy: 'Ինչպե՞ս ավարտվեց անցած կիրակիի խաղը։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'el domingo pasado (անցած կիրակի)',
    grammarTipEs: '"El domingo pasado" es un momento cerrado en el pasado, por lo que usamos Indefinido: "ganamos".',
    grammarTipHy: '«El domingo pasado» (անցած կիրակի) ավարտված անցյալ է, ուստի օգտագործվում է Indefinido՝ «ganamos»։',
    prizeAmount: 80000,
    prizeDisplay: '€80.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Hemos empatado esta semana.', textHy: 'Այս շաբաթ ոչ-ոքի ենք խաղացել։' },
      { key: 'B', textEs: 'Ganamos tres a uno.', textHy: 'Հաղթեցինք 3։1 հաշվով։' },
      { key: 'C', textEs: 'Ganábamos normalmente.', textHy: 'Սովորաբար հաղթում էինք։' },
      { key: 'D', textEs: 'Ganamos todos los días.', textHy: 'Ամեն օր հաղթում ենք։' },
    ],
  },
  {
    id: 15,
    questionEs: '¿Cómo te sentías antes de los partidos importantes cuando eras pequeño?',
    questionHy: 'Ինչպե՞ս էիր քեզ զգում կարևոր խաղերից առաջ, երբ փոքր էիր։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'cuando eras pequeño (երբ փոքր էիր՝ հոգեվիճակ)',
    grammarTipEs: 'Descripción de emociones y estados de ánimo continuos en el pasado: Imperfecto ("me sentía").',
    grammarTipHy: 'Անցյալում հոգեվիճակի և զգացողության նկարագրության համար՝ Pretérito Imperfecto («me sentía»)։',
    prizeAmount: 100000,
    prizeDisplay: '€100.000',
    isMilestone: true,
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Me he sentido bien hoy.', textHy: 'Այսօր ինձ լավ եմ զգացել։' },
      { key: 'B', textEs: 'Me sentí nervioso ayer.', textHy: 'Երեկ նյարդայնացած զգացի։' },
      { key: 'C', textEs: 'Me sentía muy nervioso.', textHy: 'Շատ նյարդայնացած էի զգում։' },
      { key: 'D', textEs: 'Me siento nervioso.', textHy: 'Նյարդայնացած եմ։' },
    ],
  },
  {
    id: 16,
    questionEs: '¿Cuántos entrenamientos has tenido esta semana?',
    questionHy: 'Քանի՞ մարզում ես ունեցել այս շաբաթ։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'esta semana (այս շաբաթ)',
    grammarTipEs: 'Con "esta semana" (lapso no terminado), empleamos Pretérito Perfecto: "he tenido".',
    grammarTipHy: '«Esta semana»-ի հետ օգտագործվում է Pretérito Perfecto՝ «he tenido» (ունեցել եմ)։',
    prizeAmount: 125000,
    prizeDisplay: '€125.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Tuve cuatro la semana pasada.', textHy: 'Անցած շաբաթ չորս մարզում ունեցա։' },
      { key: 'B', textEs: 'Tenía cuatro cada semana.', textHy: 'Ամեն շաբաթ չորս մարզում էի ունենում։' },
      { key: 'C', textEs: 'He tenido cuatro entrenamientos.', textHy: 'Չորս մարզում եմ ունեցել։' },
      { key: 'D', textEs: 'Tengo cuatro ayer.', textHy: 'Երեկ չորս մարզում ունեմ։' },
    ],
  },
  {
    id: 17,
    questionEs: '¿Qué hizo el árbitro después de la falta?',
    questionHy: 'Ի՞նչ արեց մրցավարը խախտումից հետո։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'después de la falta (խախտումից հետո՝ կոնկրետ գործողություն)',
    grammarTipEs: 'Acción puntual y consecutiva tras una falta: Pretérito Indefinido ("mostró una tarjeta").',
    grammarTipHy: 'Խախտմանն անմիջապես հաջորդած կոնկրետ ավարտուն արարք՝ Pretérito Indefinido («mostró»)։',
    prizeAmount: 150000,
    prizeDisplay: '€150.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Ha mostrado tarjetas esta temporada.', textHy: 'Այս մրցաշրջանում քարտեր է ցույց տվել։' },
      { key: 'B', textEs: 'Mostró una tarjeta amarilla.', textHy: 'Դեղին քարտ ցույց տվեց։' },
      { key: 'C', textEs: 'Mostraba una tarjeta cada día.', textHy: 'Ամեն օր քարտ էր ցույց տալիս։' },
      { key: 'D', textEs: 'Muestra una tarjeta mañana.', textHy: 'Վաղը քարտ է ցույց տալիս։' },
    ],
  },
  {
    id: 18,
    questionEs: '¿Entrenabas mucho durante las vacaciones de verano?',
    questionHy: 'Ամառային արձակուրդների ժամանակ շա՞տ էիր մարզվում։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'casi todos los días en vacaciones (գրեթե ամեն օր արձակուրդին)',
    grammarTipEs: 'Hábito repetido durante un periodo vacacional extenso: Imperfecto ("entrenaba").',
    grammarTipHy: 'Ամառային արձակուրդի ընթացքում կրկնվող գործողություն («գրեթե ամեն օր»)՝ Imperfecto («entrenaba»)։',
    prizeAmount: 175000,
    prizeDisplay: '€175.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'He entrenado hoy.', textHy: 'Այսօր մարզվել եմ։' },
      { key: 'B', textEs: 'Entrené tres horas ayer.', textHy: 'Երեկ երեք ժամ մարզվեցի։' },
      { key: 'C', textEs: 'Sí, entrenaba casi todos los días.', textHy: 'Այո, գրեթե ամեն օր մարզվում էի։' },
      { key: 'D', textEs: 'Entrenaré mañana.', textHy: 'Վաղը կմարզվեմ։' },
    ],
  },
  {
    id: 19,
    questionEs: '¿Has visto algún partido interesante esta semana?',
    questionHy: 'Այս շաբաթ որևէ հետաքրքիր խաղ դիտե՞լ ես։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'esta semana (այս շաբաթ)',
    grammarTipEs: 'Marcador temporal no concluido ("esta semana"): Pretérito Perfecto ("he visto").',
    grammarTipHy: '«Esta semana» ժամանակային նշիչով կատարված գործողություն՝ Pretérito Perfecto («he visto»)։',
    prizeAmount: 200000,
    prizeDisplay: '€200.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Vi uno el año pasado.', textHy: 'Անցած տարի մեկը դիտեցի։' },
      { key: 'B', textEs: 'Veía partidos todos los domingos.', textHy: 'Ամեն կիրակի խաղեր էի դիտում։' },
      { key: 'C', textEs: 'Sí, he visto un partido muy emocionante.', textHy: 'Այո, շատ հետաքրքիր խաղ եմ դիտել։' },
      { key: 'D', textEs: 'Veo uno mañana.', textHy: 'Վաղը մեկը դիտում եմ։' },
    ],
  },
  {
    id: 20,
    questionEs: '¿Cuándo empezaste a jugar al fútbol?',
    questionHy: 'Ե՞րբ սկսեցիր ֆուտբոլ խաղալ։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'cuando tenía seis años (երբ վեց տարեկան էի՝ սկիզբ)',
    grammarTipEs: 'El inicio puntual de una etapa en el pasado se expresa con Indefinido: "empecé".',
    grammarTipHy: 'Գործողության կոնկրետ սկիզբը անցյալում արտահայտվում է Indefinido-ով՝ «empecé» (սկսեցի)։',
    prizeAmount: 250000,
    prizeDisplay: '€250.000',
    isMilestone: true,
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'He empezado esta semana.', textHy: 'Այս շաբաթ եմ սկսել։' },
      { key: 'B', textEs: 'Empecé cuando tenía seis años.', textHy: 'Սկսեցի, երբ վեց տարեկան էի։' },
      { key: 'C', textEs: 'Empezaba todos los días.', textHy: 'Ամեն օր սկսում էի։' },
      { key: 'D', textEs: 'Empiezo a los seis años.', textHy: 'Վեց տարեկանում սկսում եմ։' },
    ],
  },
  {
    id: 21,
    questionEs: 'Cuando entrenabas de pequeño, ¿quién iba contigo?',
    questionHy: 'Երբ փոքր ժամանակ մարզվում էիր, ո՞վ էր քեզ հետ գնում։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'casi siempre de pequeño (գրեթե միշտ փոքր ժամանակ)',
    grammarTipEs: 'Acción habitual que acompañaba a otra en la niñez ("casi siempre"): Imperfecto ("iba").',
    grammarTipHy: 'Մանկության կանոնավոր սովորություն («casi siempre»՝ գրեթե միշտ)՝ Imperfecto («iba»)։',
    prizeAmount: 300000,
    prizeDisplay: '€300.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Mi padre ha ido hoy.', textHy: 'Հայրս այսօր գնացել է։' },
      { key: 'B', textEs: 'Mi padre fue ayer.', textHy: 'Հայրս երեկ գնաց։' },
      { key: 'C', textEs: 'Mi padre iba conmigo casi siempre.', textHy: 'Հայրս գրեթե միշտ ինձ հետ էր գնում։' },
      { key: 'D', textEs: 'Mi padre va conmigo mañana.', textHy: 'Հայրս վաղը ինձ հետ է գնում։' },
    ],
  },
  {
    id: 22,
    questionEs: '¿Has mejorado tu velocidad este año?',
    questionHy: 'Այս տարի արագությունդ բարելավե՞լ ես։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'este año (այս տարի)',
    grammarTipEs: 'Período temporal aún en curso ("este año"): Pretérito Perfecto ("he mejorado").',
    grammarTipHy: 'Դեռ շարունակվող ժամանակահատված («este año»՝ այս տարի)՝ Pretérito Perfecto («he mejorado»)։',
    prizeAmount: 350000,
    prizeDisplay: '€350.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Mejoré el año pasado.', textHy: 'Անցած տարի բարելավեցի։' },
      { key: 'B', textEs: 'Mejoraba cuando era pequeño.', textHy: 'Երբ փոքր էի՝ բարելավվում էի։' },
      { key: 'C', textEs: 'Sí, he mejorado bastante.', textHy: 'Այո, բավականին բարելավել եմ։' },
      { key: 'D', textEs: 'Mejoro ayer.', textHy: 'Երեկ բարելավում եմ։' },
    ],
  },
  {
    id: 23,
    questionEs: '¿Qué ocurrió cuando el portero salió de la portería?',
    questionHy: 'Ի՞նչ տեղի ունեցավ, երբ դարպասապահը դուրս եկավ դարպասից։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'inmediatamente (անմիջապես՝ ավարտուն արարք)',
    grammarTipEs: 'Acción rápida y consecutiva que interrumpe o sigue a otra: Indefinido ("marcó inmediatamente").',
    grammarTipHy: 'Դարպասապահի ելքից անմիջապես հետո կատարված ավարտուն գործողություն՝ Indefinido («marcó»)։',
    prizeAmount: 400000,
    prizeDisplay: '€400.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Hemos marcado hoy.', textHy: 'Այսօր գոլ ենք խփել։' },
      { key: 'B', textEs: 'El delantero marcó inmediatamente.', textHy: 'Հարձակվողն անմիջապես գոլ խփեց։' },
      { key: 'C', textEs: 'El delantero marcaba cada día.', textHy: 'Հարձակվողն ամեն օր գոլ էր խփում։' },
      { key: 'D', textEs: 'El delantero marca mañana.', textHy: 'Հարձակվողը վաղը գոլ է խփում։' },
    ],
  },
  {
    id: 24,
    questionEs: 'Mientras jugabas, ¿qué hacía tu entrenador?',
    questionHy: 'Մինչ դու խաղում էիր, ի՞նչ էր անում մարզիչդ։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'mientras (մինչ՝ զուգահեռ ընթացք)',
    grammarTipEs: 'Acción continua simultánea en el pasado ("mientras"): Imperfecto ("daba instrucciones").',
    grammarTipHy: 'Անցյալում զուգահեռ ընթացող գործողություն («mientras»՝ մինչ)՝ Imperfecto («daba»)։',
    prizeAmount: 450000,
    prizeDisplay: '€450.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Ha gritado hoy.', textHy: 'Այսօր բղավել է։' },
      { key: 'B', textEs: 'Gritó una vez ayer.', textHy: 'Երեկ մեկ անգամ բղավեց։' },
      { key: 'C', textEs: 'Daba instrucciones desde la banda.', textHy: 'Կողային գծից ցուցումներ էր տալիս։' },
      { key: 'D', textEs: 'Da instrucciones mañana.', textHy: 'Վաղը ցուցումներ է տալիս։' },
    ],
  },
  {
    id: 25,
    questionEs: '¿Habéis jugado contra un equipo extranjero este año?',
    questionHy: 'Այս տարի արտասահմանյան թիմի դեմ խաղացե՞լ եք։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'este año (այս տարի)',
    grammarTipEs: 'Marco temporal abierto ("este año"): Pretérito Perfecto ("hemos jugado").',
    grammarTipHy: '«Este año» (այս տարի) նշիչով կատարված փորձ՝ Pretérito Perfecto («hemos jugado»)։',
    prizeAmount: 500000,
    prizeDisplay: '€500.000',
    isMilestone: true,
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Jugamos contra uno en 2023.', textHy: '2023-ին մեկի դեմ խաղացինք։' },
      { key: 'B', textEs: 'Jugábamos contra ellos de niños.', textHy: 'Փոքր ժամանակ նրանց դեմ էինք խաղում։' },
      { key: 'C', textEs: 'Sí, hemos jugado contra un equipo italiano.', textHy: 'Այո, իտալական թիմի դեմ խաղացել ենք։' },
      { key: 'D', textEs: 'Jugaremos ayer.', textHy: 'Երեկ կխաղանք։' },
    ],
  },
  {
    id: 26,
    questionEs: '¿Qué te dijo el entrenador después del partido de ayer?',
    questionHy: 'Ի՞նչ ասաց մարզիչը երեկվա խաղից հետո։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'ayer (երեկ)',
    grammarTipEs: 'Declaración única y puntual en el día de ayer: Indefinido ("me dijo").',
    grammarTipHy: 'Երեկվա խաղից հետո կատարված հստակ ավարտուն խոսք՝ Indefinido («me dijo»)։',
    prizeAmount: 600000,
    prizeDisplay: '€600.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Me ha dicho algo hoy.', textHy: 'Այսօր ինչ-որ բան է ասել։' },
      { key: 'B', textEs: 'Me dijo que había jugado bien.', textHy: 'Ասաց, որ լավ էի խաղացել։' },
      { key: 'C', textEs: 'Me decía lo mismo todos los días.', textHy: 'Ամեն օր նույն բանն էր ասում։' },
      { key: 'D', textEs: 'Me dice mañana.', textHy: 'Վաղը ասում է։' },
    ],
  },
  {
    id: 27,
    questionEs: 'Cuando tenías diez años, ¿cuántas veces entrenabas por semana?',
    questionHy: 'Երբ տասը տարեկան էիր, շաբաթական քանի՞ անգամ էիր մարզվում։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'tres veces por semana a los diez años (կանոնավորություն մանկության տարիքում)',
    grammarTipEs: 'Frecuencia habitual en una etapa del pasado: Imperfecto ("entrenaba tres veces").',
    grammarTipHy: 'Անցյալի տարիքային փուլում կրկնվող մարզումային ռեժիմ՝ Imperfecto («entrenaba»)։',
    prizeAmount: 700000,
    prizeDisplay: '€700.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'He entrenado tres veces esta semana.', textHy: 'Այս շաբաթ երեք անգամ մարզվել եմ։' },
      { key: 'B', textEs: 'Entrené tres veces ayer.', textHy: 'Երեկ երեք անգամ մարզվեցի։' },
      { key: 'C', textEs: 'Entrenaba tres veces por semana.', textHy: 'Շաբաթական երեք անգամ էի մարզվում։' },
      { key: 'D', textEs: 'Entreno tres veces mañana.', textHy: 'Վաղը երեք անգամ եմ մարզվում։' },
    ],
  },
  {
    id: 28,
    questionEs: '¿Has aprendido algo nuevo en los entrenamientos de este mes?',
    questionHy: 'Այս ամսվա մարզումներին նոր բան սովորե՞լ ես։',
    tenseFocus: 'Pretérito Perfecto',
    tenseFocusHy: 'Անկատար ներկա / Վաղակատար',
    timeMarker: 'este mes (այս ամիս)',
    grammarTipEs: 'Resultado o aprendizaje en el mes en curso: Pretérito Perfecto ("he aprendido").',
    grammarTipHy: 'Ընթացիկ ամսում («este mes») ձեռք բերված նոր հմտություն՝ Pretérito Perfecto («he aprendido»)։',
    prizeAmount: 800000,
    prizeDisplay: '€800.000',
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Aprendí eso el año pasado.', textHy: 'Դա անցած տարի սովորեցի։' },
      { key: 'B', textEs: 'Aprendía mucho de niño.', textHy: 'Փոքր ժամանակ շատ բան էի սովորում։' },
      { key: 'C', textEs: 'Sí, he aprendido una nueva técnica de tiro.', textHy: 'Այո, հարվածի նոր տեխնիկա եմ սովորել։' },
      { key: 'D', textEs: 'Aprendo ayer.', textHy: 'Երեկ սովորում եմ։' },
    ],
  },
  {
    id: 29,
    questionEs: 'Ayer ibais perdiendo 0–1. ¿Qué pasó después?',
    questionHy: 'Երեկ 0։1 հաշվով պարտվում էիք։ Հետո ի՞նչ տեղի ունեցավ։',
    tenseFocus: 'Pretérito Indefinido',
    tenseFocusHy: 'Անցյալ կատարյալ',
    timeMarker: 'ayer / después (երեկ / հետո՝ շրջադարձային ավարտ)',
    grammarTipEs: 'Sucesión de hechos históricos y concluidos en el partido de ayer: Indefinido ("marcamos y ganamos").',
    grammarTipHy: 'Երեկվա խաղի ավարտուն շրջադարձային գործողություններ՝ Indefinido («marcamos y ganamos»)։',
    prizeAmount: 900000,
    prizeDisplay: '€900.000',
    correctKey: 'B',
    options: [
      { key: 'A', textEs: 'Hemos empatado este mes.', textHy: 'Այս ամիս ոչ-ոքի ենք խաղացել։' },
      { key: 'B', textEs: 'Marcamos dos goles y ganamos 2–1.', textHy: 'Երկու գոլ խփեցինք և հաղթեցինք 2։1։' },
      { key: 'C', textEs: 'Marcábamos dos goles cada semana.', textHy: 'Ամեն շաբաթ երկու գոլ էինք խփում։' },
      { key: 'D', textEs: 'Marcamos mañana.', textHy: 'Վաղը գոլ ենք խփում։' },
    ],
  },
  {
    id: 30,
    questionEs: 'Cuando empezó a llover durante el partido, ¿qué estabais haciendo?',
    questionHy: 'Երբ խաղի ժամանակ սկսեց անձրև գալ, ի՞նչ էիք անում։',
    tenseFocus: 'Pretérito Imperfecto',
    tenseFocusHy: 'Անցյալ անկատար',
    timeMarker: 'estábamos atacando (ընթացքի մեջ գտնվող գործողություն)',
    grammarTipEs: 'Acción en desarrollo en el momento en que ocurrió un hecho puntual ("empezó a llover"): Imperfecto continuo ("estábamos atacando y buscábamos el gol").',
    grammarTipHy: 'Անձրևի սկսվելու կոնկրետ պահին ընթացքի մեջ գտնվող գործողություն՝ Imperfecto («estábamos atacando y buscábamos»)։',
    prizeAmount: 1000000,
    prizeDisplay: '€1.000.000',
    isMilestone: true,
    correctKey: 'C',
    options: [
      { key: 'A', textEs: 'Hemos jugado hoy.', textHy: 'Այսօր խաղացել ենք։' },
      { key: 'B', textEs: 'Jugamos ayer durante una hora.', textHy: 'Երեկ մեկ ժամ խաղացինք։' },
      { key: 'C', textEs: 'Estábamos atacando y buscábamos el gol.', textHy: 'Հարձակվում էինք և փորձում էինք գոլ խփել։' },
      { key: 'D', textEs: 'Atacamos mañana.', textHy: 'Վաղը հարձակվում ենք։' },
    ],
  },
];
